// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAlHJlvCAqQkcW7hX-fPM52d6N95XB6Co',
    appId: '1:306357870345:web:3009d1a5d4add8a09f7dd8',
    messagingSenderId: '306357870345',
    projectId: 'traffica-667f6',
    authDomain: 'traffica-667f6.firebaseapp.com',
    storageBucket: 'traffica-667f6.firebasestorage.app',
    measurementId: 'G-2KK3NDMJWS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAlHJlvCAqQkcW7hX-fPM52d6N95XB6Co',
    appId: '1:306357870345:android:4705b88648ffaf6d9f7dd8',
    messagingSenderId: '306357870345',
    projectId: 'traffica-667f6',
    storageBucket: 'traffica-667f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQO2P2OM5iMpW31l8Fu1nIpLPTi9usF_k',
    appId: '1:306357870345:ios:3009d1a5d4add8a09f7dd8',
    messagingSenderId: '306357870345',
    projectId: 'traffica-667f6',
    storageBucket: 'traffica-667f6.firebasestorage.app',
    iosBundleId: 'com.example.traffica',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQO2P2OM5iMpW31l8Fu1nIpLPTi9usF_k',
    appId: '1:306357870345:ios:3009d1a5d4add8a09f7dd8',
    messagingSenderId: '306357870345',
    projectId: 'traffica-667f6',
    storageBucket: 'traffica-667f6.firebasestorage.app',
    iosBundleId: 'com.example.traffica',
  );
}
